close all; clear; clc;

% Set poles (based on zero poles diagram)
num1 = 1202.2;
num2 = 2902.5;

poles = [...
    num1 + i*num2, ...
    num1 - i*num2, ...
    num2 + i*num1, ...
    num2 - i*num1, ...
    -num1 + i*num2, ...
    -num1 - i*num2, ...
    -num2 + i*num1, ...
    -num2 - i*num1, ...
];

% Set normalized filter
N = length(poles) / 2;
[z, p, k] = buttap(N);
[num, den] = zp2tf(z, p, k);

% Set transfer function
wc = abs(poles(1));
sys = tf(num, den);